### ISSUE TITLE
How do I use atom-hg ? A possible addition to the wiki please?

### ISSUE THREAD

**Issue by visageless** [victor-torres/atom-hg#20]
I have installed atom-hg using the package manager and went into my repository and did a atom . on the command line which opened my repository in atom. I made some changes to the code and saved it but that did not show anything. What am I missing here? I am new to development hence please forgive the noob questions.

**Comment by victor-torres** [comment]
I think this is all that's necessary to use atom-hg plugin. Have you tried restarting Atom after installing the plugin? What OS do you use? You can execute `hg branch` command inside your repository? Mercurial binaries should be defined in your OS' PATH.

**Comment by visageless** [comment]
Restarting does not help. I use a Win 10 OS. # hg branch returns # default in my repository.

**Comment by victor-torres** [comment]
Look at #11. It worked after a reboot, probably because Windows added Mercurial binaries to the PATH and made them available to other applications. Can you try it?

**Comment by victor-torres** [comment]
You can also activate developer console to be able to look into errors like this and share here if necessary.

**Comment by visageless** [comment]
Thanks. Its all working now. I see mercury binaries in my OS Path now after a system restart and I think it would be helpful to know what to expect after the package has been installed. It might be just me but I feel an image of what a file diff, line diff and branch name is might help beginner users in the future.

**Comment by victor-torres** [comment]
Thanks for the suggestion. I'll do it soon.

**Comment by AHolliday** [comment]
Hi there, I just installed this package and like visageless, I am puzzled as to how to access its features.  I don't see any new options in any menus, and none of the info on this package indicates any keybindings that I should use.  The features are listed as:
- line diff in text editor
  - How do I get this to show up?
- file diff in tree view
  - Is this represented by the text colour of the file?  This seems to work for some files in a given repo, but not all...
- bookmark:branch or branch name in status bar
  - this does not appear in the status bar for the repo I'm working with.  Is that because it's on the default branch?
