### ISSUE TITLE
Blocking window 

### ISSUE THREAD

**Issue by BlaM** [victor-torres/atom-hg#3]
I'm using Atom 1.6.0 on Windows 10 with files located on a network share and each time I task switch to the editor window the whole program freezes for 2 seconds on an average sized project. Not sure if there is anything that can be changed here (asynchronous processes?), but it's too slow to be actually usable.

**Comment by victor-torres** [comment]
Hello, Dominik.

If you're using a network shared folder, there's not much I can do. The best
will be to add async support, as you've just said.

Are you comfortable forking the project and trying to make async versions of
plugin's methods?

**Comment by victor-torres** [comment]
@BlaM sorry about asking, but can't you just use a local mercurial repository?

**Comment by StefanYohansson** [comment]
network shared folder is slow. Shared folder sync requires a lot of ACK requests.

http://serverfault.com/questions/316610/what-can-make-windows-fileshares-slow-without-affecting-ping-latency-remote-des

**Comment by BlaM** [comment]
I might try to help with JavaScript - not with CoffeeScript. Sorry.

Using a local repository is not really an option right now.

**Comment by victor-torres** [comment]
They're very similar. JavaScript and CoffeeScript. If you wanna try :P  

And sorry again, but I'm just curious about why you need a remote hg repo.
Doesn't Bitbucket or something like that solve your problem?

**Comment by BlaM** [comment]
CoffeeScript has that "unreadable code" vibe going on. Sorry, too much to do, too little time to invest :hourglass: 

Not sure how Bitbucket would make anything go faster? 

I'm just a small 1-man-show web developer. My work environment is:
- NAS to store the files (Linux based)
- Windows Workstation (imports NAS via SMB)
- Linux development server (imports NAS via NFS)

I'v been thinking about going Linux-only many times, but there are just too many Windows programs I need in my daily work.

**Comment by victor-torres** [comment]
@BlaM this is what I think when we talk about distributed source control:

![Traditional versus Distributed source control](http://img.thedailywtf.com/images/201109/scm/dcm2.png)

In this case, Bitbucket would be your server, your machine and your NAS would be two of the clients.

If you edit your files in Windows and execute them in your Linux box, you should mirror them from Windows to Linux not the inverse. That would stop your Atom to freeze.

I'm not sure about how big your repository is, but Mercurial repositories are intended to be handled as local working copies. You can later configure automatic 'hg pulls' on your NAS but since code will be on Bitbucket you don't need to except as a backup thing.

This is the way I use it, except my Linux development box runs on VirtualBox and I edit my files on OS X :smiley:

**Comment by victor-torres** [comment]
We do plan in making atom-hg API asynchronous which would make the plugin itself "faster" and non-blocking, but I'm closing this issue since it's not so critical in a distributed environment.

If you or someone else want to add another detail or use case, please, comment here.

**Comment by mrstebo** [comment]
Almost finished implementing that async API (my first day doing coffeescript :wink:)

**Comment by victor-torres** [comment]
@BlaM could you check if things got better with 2.0.0 release?

**Comment by BlaM** [comment]
Will be able to try in my "home office environment" tomorrow, but it seems to be working nicely in a very similar environment at one of my customers.

**Comment by victor-torres** [comment]
Glad to know @BlaM 😃

**Comment by BlaM** [comment]
I have to update my "works nicely". It works nicely with smaller repositories. With bigger projects it still freezes the editor, so I sadly had to disable the plugin again.
